import { CounterContextProvider } from "@/context/counter.context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js" async></script>
      </head>
      <body>

        <CounterContextProvider>{children}</CounterContextProvider>
      </body>
    </html>
  );
}
